spring:
  application:
    name: tlias-web-management #随便起个名字

  #配置数据库的连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 13566861388aA-
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  servlet:
    multipart:
      # 配置文件上传的最大大小
      max-file-size: 10MB
      # 配置请求体的最大大小
      max-request-size: 100MB

#Mybatis的配置
mybatis:
  configuration:
    #配置日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射
    map-underscore-to-camel-case: true
  # 配置Mapper XML文件位置
  mapper-locations: classpath:EmpMapper.xml,classpath:EmpExprMapper.xml
    
#配置事务管理日志级别
logging:
  level:
    '[org.springframework.jdbc.support.JdbcTransactionManager]': debug

# 配置阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: javaweb-chen1
    region: cn-beijing



